version: "3.8"
services:
  mysqldb:
    image: mysql/mysql-server:latest
    restart: always
    env_file: ./.env
    # environment:
    #   - MYSQL_ROOT_HOST=${MYSQLDB_ROOT_HOST}
    #   - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    #   - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./setu
    restart: always
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.jpa.database-platform": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.datasource.driverClassName": "com.mysql.cj.jdbc.Driver",
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/rentals?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "${MYSQL_ROOT_USERNAME}",
        "spring.datasource.password" : "${MYSQL_ROOT_PASSWORD}",
        "spring.datasource.initialization-mode": "always",
        "spring.sql.init.mode": "always"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: